### ISSUE TITLE
AIR 33.1.1.300 Issue

### ISSUE THREAD

**Issue by Bilbosax** [Gamua/Adobe-Runtime-Support#533]
I just updated my sdk to AIR 33.1.1.300.  When I try to compile now, I get the following error.  I do not use an iPhone14 SDK dependancy because I don't know where to download it(let me know where to download iphone sdk if you have one), but my understanding is that the latest AIR SDK is packaged with iPhone14 SDK.  Let me know if you have any ideas.

Undefined symbols for architecture arm64:
  "_sqlite3_errcode", referenced from:
      -[APMSqliteStore errorDescriptionForDatabaseOperation:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore monitorContextForDatabaseOperation:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_errmsg", referenced from:
      -[APMSqliteStore lastErrorMessage] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_exec", referenced from:
      -[APMSqliteStore beginTransaction] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore endTransaction] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore rollbackTransaction] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_close", referenced from:
      -[APMSqliteStore closeDatabase] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_int", referenced from:
      -[APMSqliteStore validateTableWithName:requiredColumnNames:addOnColumns:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_finalize", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore executeSQLStatement:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore validateDatabaseWithError:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore finalizeAndClearStatements] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_count", referenced from:
      -[APMSqliteStore recordsForQuery:parameterValues:error:withFilter:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore validateDatabaseWithError:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_clear_bindings", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore bindValues:toStatement:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_reset", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_name", referenced from:
      -[APMSqliteStore recordsForQuery:parameterValues:error:withFilter:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_prepare_v2", referenced from:
      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_open_v2", referenced from:
      -[APMSqliteStore openAndValidateDatabase:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_bytes", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_bind_blob", referenced from:
      ___47-[APMSqliteStore bindValues:toStatement:error:]_block_invoke in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_blob", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_bind_null", referenced from:
      ___47-[APMSqliteStore bindValues:toStatement:error:]_block_invoke in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_changes", referenced from:
      -[APMSqliteStore deleteRecordsFromTableWithName:condition:parameterValues:error:] in Goo
gleAppMeasurement(APMSqliteStore_1386b8d619
Undefined symbols for architecture armv7:
  "_sqlite3_errcode", referenced from:
      -[APMSqliteStore errorDescriptionForDatabaseOperation:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore monitorContextForDatabaseOperation:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_errmsg", referenced from:
      -[APMSqliteStore lastErrorMessage] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_exec", referenced from:
      -[APMSqliteStore beginTransaction] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore endTransaction] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore rollbackTransaction] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_close", referenced from:
      -[APMSqliteStore closeDatabase] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_column_int", referenced from:
      -[APMSqliteStore validateTableWithName:requiredColumnNames:addOnColumns:error:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_finalize", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore executeSQLStatement:error:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore validateDatabaseWithError:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore finalizeAndClearStatements] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_column_count", referenced from:
      -[APMSqliteStore recordsForQuery:parameterValues:error:withFilter:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore validateDatabaseWithError:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_clear_bindings", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
      -[APMSqliteStore bindValues:toStatement:error:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_reset", referenced from:
      -[APMSqliteStore cleanUpStatement:forQuery:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_column_name", referenced from:
      -[APMSqliteStore recordsForQuery:parameterValues:error:withFilter:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_prepare_v2", referenced from:
      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_open_v2", referenced from:
      -[APMSqliteStore openAndValidateDatabase:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_column_bytes", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_bind_blob", referenced from:
      ___47-[APMSqliteStore bindValues:toStatement:error:]_block_invoke in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_column_blob", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_bind_null", referenced from:
      ___47-[APMSqliteStore bindValues:toStatement:error:]_block_invoke in GoogleAppMeasurement(APMSqliteStore_accbeb7e8050488930d8ca5cfb9fd467.o)
  "_sqlite3_changes", referenced from:
      -[APMSqliteStore deleteRecordsFromTableWithName:condition:parameterValues:error:] in Goo
gleAppMeasurement(APMSqliteStore_accbeb7e80
66e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_double", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_step", referenced from:
      -[APMSqliteStore validateTableWithName:requiredColumnNames:addOnColumns:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore tableExists:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore columnsForTableWithName:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore columnInfoForTableWithName:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore increaseColumn:byValue:inTable:condition:parameterValues:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore deleteRecordFromTableWithName:columnName:columnValue:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      -[APMSqliteStore deleteRecordsFromTableWithName:condition:parameterValues:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
      ...
  "_sqlite3_column_int64", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_type", referenced from:
      -[APMSqliteStore valueAtColumn:forStatement:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5cdc7edf8.o)
  "_sqlite3_column_text", referenced from:
      -[APMSqliteStore validateTableWithName:requiredColumnNames:addOnColumns:error:] in GoogleAppMeasurement(APMSqliteStore_1386b8d61966e81d49791bf5...

**Comment by Kelsonk** [comment]
I think the sdk already includes iPhone 14.1? Try not doing that.

**Comment by ajwfrost** [comment]
Is it possible for us to get a test case showing this error? There's something that's being linked in here and isn't working quite right but we could do with a zip of a test case where we just run the ADT tool so that we can reproduce and investigate this..

thanks

**Comment by Kelsonk** [comment]
I can give you a zip of my ane's, would that be enough? Here's my extensions tags:

```
	<extensions>
			<extensionID>com.distriqt.Adverts</extensionID>
			<extensionID>com.adcolony.airadc.AirAdColony</extensionID>
		
			<extensionID>com.distriqt.InAppBilling</extensionID>
		
			<extensionID>com.distriqt.Dialog</extensionID>
			<extensionID>com.distriqt.Core</extensionID>
			<extensionID>com.distriqt.Notifications</extensionID>
			<extensionID>com.distriqt.playservices.Ads</extensionID>
			<extensionID>com.distriqt.playservices.Base</extensionID>
			<extensionID>com.distriqt.playservices.Auth</extensionID>
			<extensionID>com.distriqt.Bolts</extensionID>
		
			<extensionID>androidx.appcompat</extensionID>
			<extensionID>androidx.browser</extensionID>
			<extensionID>androidx.core</extensionID>
			<extensionID>androidx.vectordrawable</extensionID>
			<extensionID>androidx.constraintlayout</extensionID>
		
			<extensionID>com.distriqt.playservices.AdsIdentifier</extensionID>
		
		
			<extensionID>androidx.cardview</extensionID>
			<extensionID>androidx.recyclerview</extensionID>
			<extensionID>androidx.transition</extensionID>
			<extensionID>com.android.installreferrer</extensionID>
			<extensionID>com.google.android.material</extensionID>

			<extensionID>com.google.code.gson</extensionID>
		
			<extensionID>com.distriqt.FacebookAPI</extensionID>
			<extensionID>com.distriqt.ApplicationRater</extensionID>
			<extensionID>com.google.android.play</extensionID>
		
    </extensions>
```

Drive link to ANE
https://drive.google.com/file/d/1cBScM15DTkfBkyKRcDJq35R3yVL7mA9w/view?usp=sharing

**Comment by marchbold** [comment]
Please do not share copies of our ANEs, this is not allowed as per your license.

**Comment by Kelsonk** [comment]
> Please do not share copies of our ANEs, this is not allowed as per your license. Andrew already has access to them all.

Apologies, didn't think about it.

**Comment by amorganiv** [comment]
I added this comment in issue #550

I'm seeing this same error output using AIR SDK 33.1.300 & iPhoneOS14.1.sdk:
ld: unexpected token: !tapi-tbd for architecture armv7
ld: unexpected token: !tapi-tbd for architecture arm64
Compilation failed while executing : ld64

Also, I'm using the distriqt/ANE-InAppBilling. The app builds correctly using AIR SDK 33.1.1.98 & iPhoneOS13.1.sdk

**Comment by amorganiv** [comment]
Michael... I was able to build the app with AIR SDK 33.1.300 after removing the reference to '-platformsdk iPhoneOS14.1.sdk'. It installed correctly and I completed a sandbox purchase. Is the adt command build '-platformsdk iPhone' no longer necessary to package the distriqt/inAppBilling ane for ipa?

**Comment by marchbold** [comment]
@amorganiv with 33.1.1.300 Harman have included the iOS 14 SDK so you don't have to use the platformsdk option. However 300 is really buggy so I can't suggest you use it currently.

**Comment by amorganiv** [comment]
Thank you for the update!

**Comment by vetaldnepr** [comment]
Hello, I only get the same error when I use Adcolony ANE. If I use ANEs from Distriqt, there is no such error.
AIR SDK 33.1.1.575,
<extensionID>com.adcolony.airadc.AirAdColony</extensionID>
Error: Compilation failed while executing : ld64
