### ISSUE TITLE
iOS simulator - framework not found AppTrackingTransparency

### ISSUE THREAD

**Issue by ElectricFrenchFries** [Gamua/Adobe-Runtime-Support#546]
I am getting some errors attempting to use the iOS Simulator. My app works on real devices. 

When I attempt to run the app in the simulator, using the Adverts ANE from Distriqt, I get an error (see Error 1 below). 

I am using the latest ANE versions, with the Distriqt supplied iOS SDK 14.1, attempting to run the simulator at the following path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk

Using Air SDK 33.1.1.259, if I remove all references to the Adverts ANE, the app builds and installs successfully to the simulator.

I have also attempted to build using Air SDK 33.1.1.300. I get the same AppTrackingTransparency error. I can resolve that error by removing the Adverts ANE, however a new error (see Error 2 below) is then presented. 

I raised an issue in the private repo for the Adverts ANE. Distriqt support (@marchbold ) suggested that I also raise an issue here.

##### Environment 

- AIR SDK version: 33.1.1.259, 33.1.1.300
- Device OS: Simulator
- Device version: iPhone 11
- Development IDE: IntelliJ
- Development OS: Mac OS

###### Error 1
ld: framework not found AppTrackingTransparency
Compilation failed while executing : ld64

###### Error 2
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      __ZN26PlatformPrimitiveSocketTCP16HaveIncomingDataEv in libRuntimeInterpreter.x86-simulator-air.a(OSXPrimitiveSocket.o)
      __ZN14PlatformSelect12WaitForEventEjPb in libRuntimeInterpreter.x86-simulator-air.a(OSXPrimitiveSocket.o)
      __ZN20PlatformSecureSocket17WaitOnSocketErrorEiNS_15WaitReadOrWriteEb in libRuntimeInterpreter.x86-simulator-air.a(CTSecureSocket.o)
      __ZN17MacDatagramSocket11ReceiveImplEPhPiR11FlashStringRiS3_S4_i in libRuntimeInterpreter.x86-simulator-air.a(OSXDatagramSocket.o)
ld: symbol(s) not found for architecture x86_64
Compilation failed while executing : ld64

**Comment by ajwfrost** [comment]
Thanks, yes we'd also found this and it does appear to be from our use of the "FDSET" macro in the socket handling. Currently trying to find out a way to solve this that would work across all the different MacOS versions...

**Comment by jimmymjing** [comment]
I'm getting the same error while I'm trying to debug on a real device.

Error 1
ld: framework not found AppTrackingTransparency
Compilation failed while executing : ld64

Environment
AIR SDK version: 33.1.1.300
Device OS:  iPhone X
Development IDE: FB 4.7
Development OS: Windows

**Comment by triplumix** [comment]
Still getting this error.
AIR 33.1.1.406

**Comment by ajwfrost** [comment]
@triplumix  could you please try using the adt.jar from the below link? If you find the SDK folder and go into "lib", this is where the new adt.jar needs to go - worth backing up the existing one first though..

https://transfer.harman.com/message/A30SIcuQ5NoPo9KyE3QQxA

This should fix the problem with the FS_SET unreferenced variable. There should be an 'AppTrackingTransparency.framework' file in the latest SDKs though so please let me know if you're still seeing that part of this error report..

thanks

**Comment by edicsa** [comment]
Still getting this error.
AIR 33.1.1.444
